version: '3'

services:
  reverseproxy:
    image: nginx:alpine
    ports:
      - 81:81
      - 82:82
    volumes:
      - ./scripts/nginx.conf:/etc/nginx/nginx.conf
    restart: always
  web:
    depends_on:
      - reverseproxy
    image: ajitemsahasrabuddhe/php-apache:bionic-7.2-dev
    volumes:
      - ./web:/var/www/html
      - ./scripts/000-default.conf:/etc/apache2/sites-available/000-default.conf
    restart: always
  hub:
    depends_on:
      - reverseproxy
    image: ajitemsahasrabuddhe/php-apache:bionic-7.2-dev
    volumes:
      - ./hub:/var/www/html
      - ./scripts/000-default.conf:/etc/apache2/sites-available/000-default.conf
    restart: always
